### ISSUE TITLE
Hotkeys for ‘Capture Top’ and ‘Capture All’

### ISSUE THREAD

**Issue by Evotron** [billforsternz/tarrasch-chess-gui#14]
I would like to make a feature request for hotkeys for ‘Capture Top’ and ‘Capture All’.

**Comment by friscodelrosario** [comment]
What does that mean? Those aren't things I expect to do during a game, or during annotation of a game.

**Comment by billforsternz** [comment]
> _What does that mean? Those aren't things I expect to do during a game, or during annotation of a game._
> 
> Edit: Oh, I see Capture Top and Capture All refer to the engine output. And I asked myself: Why would anyone want a keyboard command for this?
> 
> I imagine one might want a key command for this if reviewing a game and wanting the engine analysis for every move? Or many moves? If that's the case, I know Fritz has an auto-annotate feature that captures all the analysis for moves that are, say, more than 2.00 better than the one played. Maybe Bill would think that useful. But otherwise, is that a command you need so often that a keycommand is warranted?

I agree that this is not something I am ever likely to implement. I should prune issues sometimes, so I will close this one.
