### ISSUE TITLE
Engine evaluation of a current position for both sides

### ISSUE THREAD

**Issue by ungarcontriste** [billforsternz/tarrasch-chess-gui#16]
I've recently discovered this gui and wonder if there's a way to set up a position and evaluate it for both sides?

I guess it's only possible to start engine analysis and evaluate possible lines and for a side which is about to move (e.g. for white on screenshot below).

![Screenshot_4](https://user-images.githubusercontent.com/16438681/68061642-f3a07d80-fd16-11e9-9132-0178727fac37.png)

**Comment by billforsternz** [comment]
I think the current behaviour is conventional and optimal really. The "side to move" is an important part of the current position. No chess position makes sense unless you know who is to move. Of course you can toggle the "side to move" and re-analyse, but then you are analysing two different positions (same pieces on same squares, but a different side to move). Some positions don't allow this - if one side is in check, it's only a legal position if that side is to move (obviously).

The variations, and evaluation scores shown are all dependent on the current side to move (of course).
