### ISSUE TITLE
Color/size preferences don't persist in Linux

### ISSUE THREAD

**Issue by friscodelrosario** [billforsternz/tarrasch-chess-gui#19]
Tarrasch v. 3.12b
Elementary OS 18.04.4 LTS
Linux 5.4.0-42-generic

Changes made in Options -> General don't persist in next session.

No problem redoing them each time, but in at least one case, there are very many.

**Comment by billforsternz** [comment]
On holiday this week, will take a look next week. Do some experiments, you
might be able to work around this one yourself. Find the Tarrasch.ini file
and experiment. Why isn't Tarrasch finding it? I think ~/Tarrasch is the
default directory, maybe the directory where Tarrasch executable lives is
worth trying. Do other options (not General) persist?

Bill.
