### ISSUE TITLE
Startup looks for opening book in Tarrasch home folder, but it's in /install in Linux

### ISSUE THREAD

**Issue by friscodelrosario** [billforsternz/tarrasch-chess-gui#24]
![Screenshot from 2020-09-03 05 52 37](https://user-images.githubusercontent.com/59985/92117608-41a86680-edaa-11ea-8ae4-340bc22adbb7.png)

**Comment by billforsternz** [comment]
The Linux build is pretty much a side effect really. A lot of effort was put in to making Tarrasch work as easily as possible out of the box for casual Windows users. Linux is a complete contrast. I found (almost to my surprise) that it worked well as a binary/executable. But I haven't (yet?) tried to make any kind of installation procedure. So the user has to compile it and then assemble things like book files, databases and engines themselves. I don't expect this to change in the short term. My fondest wish would be for some collaborator to show up with an interest in things like this which are quite orthogonal to my own interests.

Speaking more directly to the point of the comment - there are certainly no dependencies anywhere that depend on book.pgn being anywhere in particular. The book file is simply an arbitrary PGN file, its location is a configuration option and it can be anywhere the user has write access (write access so Tarrasch can make a 'compiled' shadow file).
