### ISSUE TITLE
Can't find a Markdown viewer  that plays nice with Publish output

### ISSUE THREAD

**Issue by friscodelrosario** [billforsternz/tarrasch-chess-gui#26]
I've tried several online viewers and two Chrome extensions but none displays Tarrasch CSS styles.

**Comment by billforsternz** [comment]
This is an undocumented extra for experts feature that isn't currently fit for purpose admittedly. But it can work reasonably well, see for example the NZ Chess Bulletins at newzealandchess.co.nz which I publish with unmodified Tarrasch, and the markdown -> html tool Poole https://hg.sr.ht/~obensonne/poole
