### ISSUE TITLE
Insert null move

### ISSUE THREAD

**Issue by friscodelrosario** [billforsternz/tarrasch-chess-gui#28]
For annotators, it's nice to have the ability to insert a null move. Say you want to show the result of a threat if it's carried out.  

If you want that note *before* the actual move played (after White's 26th move, you want to say ahead of Black's move: "White threatens 27. Qxa7!, and then if 27...Rxa7, blah blah blah), you have to mouse in a dummy move (like 26...Kg8-h8 if that doesn't affect the position) before mousing the rest of your variation.

The drawbacks there are that 1) You have to remember to edit the dummy move out of the text before publishing, and 2) you don't like sharing the PGN because how do you explain 26...Kg8?

Some packages give you an "insert null move" option for Black's 26th move. Engine users can then see analysis as though Black passes move 26, and White gets to carry out the deadly threat at move 27. 

(This was actually a huge improvement in Deep Blue toward the end of its life. I don't know how they handled that kind of analysis before they implemented null moves. It's how humans *ought* to think at the board. When the opponent moves, you should ask yourself "what if I did nothing about that, and went ahead with my own schemes?" and the way to calculate that is to imagine yourself passing your move. Similarly, when humans are considering a move that threatens, they have to imagine the opponent making a null move to see if the threat actually gets anywhere.)

**Comment by friscodelrosario** [comment]
For example:

White could give Black a way to go wrong with (16.Qd2 , preparing to recapture on d4 with the knight, while dxc5 includes a discovered attack. Then  16...Qxb3?  is a blunder, because 17.dxc5 **null move here** menaces 18.Nd4  to fork, and perhaps trap the black queen [ 18...Qa4 19.Bb5 ]. )

For lack of a null move feature, I used 17...Be4 as a placeholder, so the PGN parser would work with 18. Nd4, etc.

**Comment by billforsternz** [comment]
As mentioned in another one of these recent issues, I am on holiday for a
few more days, but I will quickly mention that you can enter a null move by
adding a double hyphen annotation then promoting it to "moves" ( it's in
the FAQ on triplehappy.com)

Bill

**Comment by friscodelrosario** [comment]
Right! I found that buried in a PGN spec minutes ago.
