### ISSUE TITLE
Make broke on Ubuntu 18.04 install

### ISSUE THREAD

**Issue by friscodelrosario** [billforsternz/tarrasch-chess-gui#41]
frisco@galliumos:~/tarrasch-chess-gui$ make
make -C src
make[1]: Entering directory '/home/frisco/tarrasch-chess-gui/src'
g++ -c -g -std=c++11 `wx-config --cxxflags` Book.cpp -o Book.o
g++ -c -g -std=c++11 `wx-config --cxxflags` MemoryPositionSearch.cpp -o MemoryPositionSearch.o
g++ -c -g -std=c++11 `wx-config --cxxflags` ClipboardDialog.cpp -o ClipboardDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` Tabs.cpp -o Tabs.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PositionDialog.cpp -o PositionDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` Database.cpp -o Database.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PgnDialog.cpp -o PgnDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PgnFiles.cpp -o PgnFiles.o
g++ -c -g -std=c++11 `wx-config --cxxflags` GamePrefixDialog.cpp -o GamePrefixDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` Session.cpp -o Session.o
g++ -c -g -std=c++11 `wx-config --cxxflags` GameDetailsDialog.cpp -o GameDetailsDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PopupControl.cpp -o PopupControl.o
g++ -c -g -std=c++11 `wx-config --cxxflags` WinUciInterface.cpp -o WinUciInterface.o
g++ -c -g -std=c++11 `wx-config --cxxflags` GameView.cpp -o GameView.o
g++ -c -g -std=c++11 `wx-config --cxxflags` DbPrimitives.cpp -o DbPrimitives.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PackedGameBinDb.cpp -o PackedGameBinDb.o
g++ -c -g -std=c++11 `wx-config --cxxflags` BookDialog.cpp -o BookDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` CompactGame.cpp -o CompactGame.o
g++ -c -g -std=c++11 `wx-config --cxxflags` MoveTree.cpp -o MoveTree.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PlayerDialog.cpp -o PlayerDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` PatternDialog.cpp -o PatternDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` TrainingDialog.cpp -o TrainingDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` Atom.cpp -o Atom.o
g++ -c -g -std=c++11 `wx-config --cxxflags` BinDb.cpp -o BinDb.o
g++ -c -g -std=c++11 `wx-config --cxxflags` main.cpp -o main.o
g++ -c -g -std=c++11 `wx-config --cxxflags` MonitorUsagePattern.cpp -o MonitorUsagePattern.o
g++ -c -g -std=c++11 `wx-config --cxxflags` Undo.cpp -o Undo.o
g++ -c -g -std=c++11 `wx-config --cxxflags` GamesDialog.cpp -o GamesDialog.o
g++ -c -g -std=c++11 `wx-config --cxxflags` GameDocument.cpp -o GameDocument.o
g++ -c -g -std=c++11 `wx-config --cxxflags` CompressMoves.cpp -o CompressMoves.o
CompressMoves.cpp: In member function ‘std::__cxx11::string CompressMoves::ToNaturalMoves(const string&, const string&)’:
CompressMoves.cpp:417:13: error: ‘_itoa’ was not declared in this scope
             _itoa(nbr++, buf, 10);
             ^~~~~
Makefile:10: recipe for target 'CompressMoves.o' failed
make[1]: *** [CompressMoves.o] Error 1
make[1]: Leaving directory '/home/frisco/tarrasch-chess-gui/src'
Makefile:6: recipe for target 'srccode' failed
make: *** [srccode] Error 2

**Comment by rchastain** [comment]
Same error here, on Linux Mageia.

**Comment by rchastain** [comment]
It's easy to fix.

```c
            // _itoa(nbr++, buf, 10);
            sprintf(buf, "%d", nbr++);
```

After that compilation is successful (Linux Mageia, GCC 10.4.0).
