### ISSUE TITLE
Fixed time feature

### ISSUE THREAD

**Issue by laocmo** [billforsternz/tarrasch-chess-gui#6]
I've played around seriously with chess computers/programs since the 1980's. One feature I really liked on all those machines was the "fixed think time" for the computer feature. I could easily check my progress as a chess player by starting off letting the machine think for say, 5 seconds. After I had a lot of fun beating it at that level I went to 10 seconds, etc. Eventually on the stronger computers and programs I stalled out at about 3 minutes computer think time. Of course I took all the time I needed. It was a lot of fun. Hardly real world tournament conditions, but a great learning tool. I think your program would benefit greatly if the human, especially beginners,  was allowed to set the think time for the machine. Forget about tournament play and just seek the highest think time you can consistently beat the machine is great fun. Sounds like it would not be too difficult to implement that feature in your great little program!

**Comment by billforsternz** [comment]
Don't worry - your feature will definitely be in the Tarrasch V3 Beta that's scheduled for about a week's time. But I'll leave this issue open until that's publically available.

**Comment by billforsternz** [comment]
Tarrasch V3 Beta now released, including your feature. I hope you like it.

**Comment by laocmo** [comment]
Lovin' it Bill! That new feature makes it
        perfect!
    Larry
    
    
    On 7/12/2016 12:49 AM, billforsternz
      wrote:
    
    
      Tarrasch V3 Beta now released, including your feature. I hope
        you like it.
      �
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by billforsternz** [comment]
Thanks Larry, glad you're happy.
Bill.
