### ISSUE TITLE
When opening lattest update I get message "Cannot open c:\Program Files(x86)\Tarrasch\book.pgn_compiled for writing"

### ISSUE THREAD

**Issue by laocmo** [billforsternz/tarrasch-chess-gui#7]
Installed your latest update. When opening program I get message "Cannot open c:\Program Files(x86)\Tarrasch\book.pgn_compiled for writing" Also can't make engine use the book.pgn at all. Kibitzer mode shows engine thinking of the normal book moves, but it never makes them. Also when making engine think for some number of seconds, I don't know which box to type in the time. There are two boxes that will accept different numbers. Why two boxes. I only need one that will accept 5, 10, 15, etc seconds.

**Comment by billforsternz** [comment]
I cannot reproduce this problem, but clearly something has gone wrong with the (re)installation process. It doesn't look as if you currently have an opening book active. If you did there would be a green box visible saying "10 book moves" in the opening position. The book is supposed to be in a Tarrasch directory within your main Windows Documents folder. You could use the Options > Opening Book menu to browse your way to an existing book file (from a previous successful installation). For example my book is at C:\Users\Bill\Documents\Tarrasch\book.pgn. If this doesn't work you could try uninstalling Tarrasch (Control Panel  > Programs), then reinstalling. If that doesn't work please contact me directly.

The box you are looking for is Options > Clock Settings > New game: engine > Time (seconds):

That will apply from the next game.

**Comment by billforsternz** [comment]
Whoops pressed Close and Comment instead of just Comment

**Comment by billforsternz** [comment]
Whoops pressed Close and Comment instead of just Comment

**Comment by laocmo** [comment]
Bill,
I reinstalled everything. Same results. Program couldn't find a critical file. Finally I found "Reset to factory defaults" button. That worked. Everything is running smoothly now. No idea what it did, but it worked.

**Comment by Roger12345678901** [comment]
Tarrasch will not open. It gives me an error message that it cannot find book.pgn, but I checked and book.pgn is in the file where it says that it cannot find it.

**Comment by javacertified** [comment]
Had the same problem as laocmo; same solution worked: "reset to factory defaults."
