### ISSUE TITLE
another logical stuff

### ISSUE THREAD

**Issue by maddin200** [billforsternz/tarrasch-chess-gui#9]
\src\thc.cpp line 7467 + 7817
should be probably && 
if( '1'<=dst_rank || dst_rank<='8' )

**Comment by billforsternz** [comment]
Another nice catch thanks.

These both cause flaws in handling ill-formed .pgn input. Input moves like "Nfdx" is handled using logic meant for correctly formed input like "Nfd2", with a resulting out of range destination square as "dx" is parsed as a square with no further error check. Nothing good could come from that.

I am very grateful to maddin200 for finding and reporting this problem. I will fix in the next release, within the next month, and close the issue then.

**Comment by billforsternz** [comment]
Sorry, still haven't issued a new release, and I probably won't issue a new release until February. I will belatedly push a fix to this issue to the development branch today.

**Comment by billforsternz** [comment]
Finally closing this issue after V3.06a pre-release
